### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Signed-off-by: CaptTrews <capttrews@gmail.com>
Depends-On: https://github.com/ansible/ansible/pull/62596

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ff10412d253beee93c56b48a9fb250646f7350c9

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now b7ad4f9c27ba05d1938b96d82a5038cb9a572b0f

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5897081e91f99f0967980d25b8a7bc207ad6d904

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
