### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible/pull/60947
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/196
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/199
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 840e2a75bbbd8cace8bf0a903b311b8379d0798d

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 56447ab20abe6b1db9a6ee972469d13fdecd9ca0

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now e64f9c1c0f1b158f10384cd913375b0f1c997e4f

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 3d2984249a36c2149e41816cbedd456eb9183e7d

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 81512e97ae4bf6e0442340c8fccb1b376bcd639d

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
