### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 3ca934fc539743ddbcd260ab3d1a0287f18b6392

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c1b748c163fa1745331c0dddc7191d35e3fe5a33

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 0cb0e1d4fc1be5822df8ea0b55bce0fedaad1086

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now f1330bf8250b38ca78e17ed69166a9b6e9d5cce4

**Pull request merged**
