### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5c02829fbf39d8fd8aa2e9cc4a38d2c7da0d285d

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 10bdab65e9b7fdd61f11d8cf37fde030e9c14b47

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now b77020668659aac95c8ab6b506a9193dfaac92bd

**Pull request closed without merging**
